Complete initial utility script

diff --git a/templates/utility_script.j2 b/templates/utility_script.j2
--- a/templates/utility_script.j2
+++ b/templates/utility_script.j2
@@ -8,3 +8,244 @@
 # Style:     ENV_VAR, GLOBAL_VAR, GLOBAL_READONLY_VAR, func_local_var, my_func
 ################################################################################
 
+# GLOBAL VARS:
+
+# Constants
+PROG_NAME="$(basename "${0}")"
+readonly PROG_NAME
+UDISKCTL_CMD='{{ udisks_main_cmd }}'
+readonly UDISKCTL_CMD
+
+# Mutable User Cmd Option Selections
+PRINT_HELP_MENU='false'
+MOUNT_DEVICE='false'
+UNMOUNT_DEVICE='false'
+
+# Mutable User Options
+DEVICE_PATH=""
+
+# LOCAL FUNCTIONS:
+
+print_usage() {
+  prog_name_num_chars="$(printf "%s" "${PROG_NAME}" | wc -m)"
+  leading_indent=''
+  i=0
+  while [ "${i}" -lt "${prog_name_num_chars}" ]; do
+    leading_indent="${leading_indent} "
+    i=$((i + 1))
+  done
+
+  printf "USAGE:\n"
+  printf "  %s  -h|--help\n" "${PROG_NAME}"
+  printf "  %s  -m|--mount    -D <path>\n" "${PROG_NAME}"
+  printf "  %s  -u|--unmount  -D <path>\n" "${PROG_NAME}"
+  printf "DETAILS:\n"
+  printf "  -h, --help\n"
+  printf "      print this help message\n"
+  printf "  -m, --mount\n"
+  printf "      mount a device\n"
+  printf "  -u, --unmount\n"
+  printf "      unmount a device\n"
+  printf "  -D <path>, --device-path=<path>\n"
+  printf "      path to device (e.g. /dev/da0p1)\n"
+  printf "EXIT CODES:\n"
+  printf "    0  ok\n"
+  printf "   10  mount/unmount error\n"
+  printf "  255  usage or options error\n"
+}
+
+get_cmd_opts() {
+  while getopts ':hmuD-:' option; do
+    short_opt_arg="${OPTARG}"
+    case "${option}" in
+      h)  handle_print_help_menu ;;
+      m)  handle_mount ;;
+      u)  handle_unmount ;;
+      D)  handle_device_path "${short_opt_arg}" ;;
+      -)  long_opt_name="${OPTARG}"
+          long_opt_arg="${OPTARG#*=}"
+          case ${long_opt_name} in
+            help)             handle_print_help_menu ;;
+            help=*)           handle_illegal_long_option_arg "${long_opt_name}" ;;
+            mount)            handle_mount ;;
+            mount=*)          handle_illegal_long_option_arg "${long_opt_name}" ;;
+            unmount)          handle_unmount ;;
+            unmount=*)        handle_illegal_long_option_arg "${long_opt_name}" ;;
+            device-path=?*)   handle_device_path "${long_opt_arg}" ;;
+            device-path*)     handle_missing_long_option_arg "${long_opt_name}" ;;
+            '')               break ;; # non-option arg starting with '-'
+            *)                handle_unknown_option "${long_opt_name}" ;;
+          esac ;;
+      \?) handle_unknown_option "${short_opt_arg}" ;;
+    esac
+  done
+}
+
+exit_with_cleanup() {
+  err_code="${1}"
+  exit "${err_code}"
+}
+
+print_err_msg() {
+  err_msg="${1}"
+  printf "ERROR:\n%s: %s\n" "${PROG_NAME}" "${err_msg}"
+}
+
+quit_with_err_msg() {
+  err_msg="${1}"
+  err_code="${2}"
+  print_err_msg "${err_msg}"
+  exit_with_cleanup "${err_code}"
+}
+
+quit_if_rc_not_zero() {
+  cmd_exit_code="${1}"
+  err_msg="${2}"
+  script_exit_code="${3}"
+  if [ "${cmd_exit_code}" != 0  ]; then
+    quit_with_err_msg "${err_msg}" "${script_exit_code}"
+  fi
+}
+
+try_silent_with_exit() {
+  cmd="${1}"
+  err_msg="${2}"
+  err_code="${3}"
+
+  eval "${cmd}"
+  exit_code="${?}"
+  if [ "${exit_code}" != 0 ]; then
+    quit_with_err_msg "${err_msg}" "${err_code}"
+  fi
+}
+
+try_silent_print_with_exit() {
+  cmd="${1}"
+  op_descrip="${2}"
+  err_code="${3}"
+
+  printf "Now %s with \"%s\"...\n" "${op_descrip}" "${cmd}"
+  err_msg="error ${op_descrip}"
+  try_silent_with_exit \
+    "${cmd}" \
+    "${err_msg}" "${err_code}"
+}
+
+try_total_silent_with_exit() {
+  cmd="${1}"
+  op_descrip="${2}"
+
+  printf "Now %s with \"%s\"...\n" "${op_descrip}" "${cmd}"
+  eval "${cmd}" 1> /dev/null 2>&1
+}
+
+handle_unknown_option() {
+  short_opt_letter_or_long_opt_name="${1}"
+  err_msg="unknown option \"${short_opt_letter_or_long_opt_name}\""
+  quit_with_err_msg "${err_msg}" 255
+}
+
+handle_illegal_long_option_arg() {
+  long_opt_name="${1}"
+  err_msg="illegal argument in \"${long_opt_name}\""
+  quit_with_err_msg "${err_msg}" 255
+}
+
+handle_missing_long_option_arg() {
+  long_opt_name="${1}"
+  err_msg="missing argument for option \"${long_opt_name}\""
+  quit_with_err_msg "${err_msg}" 255
+}
+
+handle_print_help_menu() {
+  if [ "${MOUNT_DEVICE}" = 'true' ] || \
+     [ "${UNMOUNT_DEVICE}" = 'true' ]; then
+    quit_with_err_msg "mutually exclusive options selected" 255
+  fi
+  PRINT_HELP_MENU='true'
+}
+
+handle_mount() {
+  if [ "${PRINT_HELP_MENU}" = 'true' ] || \
+     [ "${UNMOUNT_DEVICE}" = 'true' ]; then
+    quit_with_err_msg "mutually exclusive options selected" 255
+  fi
+  MOUNT_DEVICE='true'
+}
+
+handle_unmount() {
+  if [ "${PRINT_HELP_MENU}" = 'true' ] || \
+     [ "${MOUNT_DEVICE}" = 'true' ]; then
+    quit_with_err_msg "mutually exclusive options selected" 255
+  fi
+  UNMOUNT_DEVICE='true'
+}
+
+handle_device_path() {
+  DEVICE_PATH="${1}"
+
+  try_silent_with_exit \
+    "test -b ${DEVICE_PATH}" \
+    "\"${DEVICE_PATH}\" must be a block device" 255
+}
+
+check_running_as_root() {
+  if [ "$(id -un)" != 'root' ]; then
+    quit_with_err_msg "must run this script as root for this operation" 255
+  fi
+}
+
+check_mount_option() {
+  if [ "${DEVICE_PATH}" = '' ]; then
+    quit_with_err_msg "\"--device-path\" option must be specified" 255
+  fi
+}
+
+check_unmount_option() {
+  if [ "${DEVICE_PATH}" = '' ]; then
+    quit_with_err_msg "\"--device-path\" option must be specified" 255
+  fi
+}
+
+do_print_help_menu() {
+  print_usage
+}
+
+do_mount_device() {
+  check_running_as_root
+  check_mount_option
+
+  try_silent_print_with_exit \
+    "${UDISKCTL_CMD} mount -b \"${DEVICE_PATH}\"" \
+    "mounting device" 10
+}
+
+do_unmount_device() {
+  check_running_as_root
+  check_unmount_option
+
+  try_silent_print_with_exit \
+    "${UDISKCTL_CMD} unmount -b \"${DEVICE_PATH}\"" \
+    "unmounting device" 10
+}
+
+# MAIN SCRIPT:
+
+main() {
+  get_cmd_opts "$@"
+
+  if [ "${PRINT_HELP_MENU}" = 'true' ]; then
+    do_print_help_menu
+  elif [ "${MOUNT_DEVICE}" = 'true' ]; then
+    do_mount_device
+  elif [ "${UNMOUNT_DEVICE}" = 'true' ]; then
+    do_unmount_device
+  else
+    quit_with_err_msg "no valid option selected" 255
+  fi
+
+  exit_with_cleanup 0
+}
+
+main "$@"
+
